title: My Blog

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"

sidebar:
  nav: "docs" 
  
comments:
  provider: "utterances"
  utterances:  
    theme: "github-dark" 
